docker:
  image: yegor256/blog

install: |
  sudo locale-gen en_US en_US.UTF-8
  sudo dpkg-reconfigure locales
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  bundle install
  rake
