# More about this file: https://docs.travis-ci.com/user/customizing-the-build

language: ruby
sudo: false
rvm:
  - 2.2.2
#   - 2.5.1
cache: bundler
branches:
  only:
    - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
install:
  - travis_retry bundle install
script:
  - rake

