title: driver733's blog
email: yakushin@terpmail.umd.edu
description: >
  Personal blog of Mikhail (@driver733) Yakushin about programming.
baseurl: ""
url: "http://driver733.com"
twitter_username: driver733
github_username: driver733
markdown: kramdown
author:
  name: "Mikhail Yakushin"
  email: yakushin@terpmail.umd.edu
encoding: utf-8
timezone: Europe/Moscow
permalink: :year/:month/:day/:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - LICENSE.txt

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->

feed:
  title: driver733.com
  subtitle: driver733's blog
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
