title: Mikhail @driver733 Yakushin's blog
email: yakushin@terpmail.umd.edu
description: Personal blog of Mikhail @driver733 Yakushin about programming.
url: "https://www.driver733.com"
twitter_username: driver733
github_username: driver733
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
author:
  first_name: "Mikhail"
  last_name: "Yakushin"
  username: "driver733"
  gender: "male"
  email: yakushin@terpmail.umd.edu
encoding: utf-8
timezone: Europe/Moscow
permalink: :year/:month/:day/:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - LICENSE.txt
plugins:
  - jekyll-feed
  - jekyll-bits
  - jekyll-paginate
  - jekyll-plantuml
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-related-posts
paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->
feed:
  title: Mikhail @driver733 Yakushin's blog
  subtitle: Personal blog of Mikhail @driver733 Yakushin about programming.
  path: rss.xml
sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      title: Mikhail @driver733 Yakushin's blog
      description: Personal blog of Mikhail @driver733 Yakushin about programming.
  -
    scope:
      path: "static"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
